// <auto-generated />
namespace NorthwindEntity.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddNorthwindMigration_11 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddNorthwindMigration_11));
        
        string IMigrationMetadata.Id
        {
            get { return "201805240713225_AddNorthwindMigration_1.1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
